### ISSUE TITLE
Use JavaScript to send text to html, footer and header.

### ISSUE THREAD

**Issue by Coderwe1** [Coderwe1/GalaxyOS#9]
We have a lot of html files and changing the footers and headers havent been more harder.

I conclude we add a `text.js` file that will handle the text display in header/footer.

What needs to be done
- [x] add `text.js` file
- [x] link the header/footer with `text.js`
- [x] when body loads display the text

Why?
because we need faster and more efficient ways to edit our footer and header text.
#8 messy

**Comment by oxendy** [comment]
So, what you want is that you make a file that stores all the headers and footers of the site?

**Comment by Coderwe1** [comment]
basically yes

**Comment by HGT-123** [comment]
So this is done?
